module.exports = {
  cart: require("./cart"),
  category: require("./category"),
  collectionProduct: require("./collectionProduct"),
  collectionProductItem: require("./collectionProductItem"),
  discount: require("./discount"),
  discountUsage: require("./discountUsage"),
  finishing: require("./finishing"),
  material: require("./material"),
  order: require("./order"),
  orderItem: require("./orderItem"),
  // payment: require("./payment"),
  product: require("./product"),
  productColor: require("./productColor"),
  productImage: require("./productImage"),
  productSize: require("./productSize"),
  productVariant: require("./productVariant"),
  review: require("./review"),
  shipping: require("./shipping"),
  type: require("./type"),
  user: require("./user"),
  userProfil: require("./userProfile"),
  wishlist: require("./wishlist"),
};
